### ISSUE TITLE
Customize "cannot initialize statement expression" for inspect

### ISSUE THREAD

**Issue by bcardosolopes** [bcardosolopes/llvm-project#19]
Not wrong but misleading since it's re-using the statement expression mechanism for diagnostics. Have a more friendly message.

void c(int x) {
  inspect(x) -> void {
    __ => 3;
    // error: cannot initialize statement expression
    // result of type 'void' with an rvalue of type 'int'
  };
  return w;
}

**Comment by dansarginson** [comment]
I have a PR for this. We're actually trying to fire the correct diagnostic but this reveals a parsing issue elsewhere.

**Comment by bcardosolopes** [comment]
Great. The issue, IIRC, is due to the reuse of statement expressions infra for some of the parsing, we don't necessarily need to dup it, there might be some easy customization we can apply.

**Comment by dansarginson** [comment]
You're right. I'll keep going on this but the PR isn't as ready as I'd hoped. I needed to rethink my approach.
