### ISSUE TITLE
Unit test failures in PatternMatching tests

### ISSUE THREAD

**Issue by steve-downey** [bcardosolopes/llvm-project#8]
Failing tests, among a few others:
    Clang-Unit :: ASTMatchers/./ASTMatchersTests/PatternMatching.MatchesInspect
    Clang-Unit :: ASTMatchers/./ASTMatchersTests/PatternMatching.MatchesPattern

Built with:
CXX=clang++-11  CC=clang-11  cmake -DCMAKE_INSTALL_PREFIX=~/install/llvm-pattern/   -DCMAKE_BUILD_TYPE=Release  -DLLVM_ENABLE_ASSERTIONS=yes -DLLVM_USE_LINKER=lld -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_ENABLE_PROJECTS="clang" -DCOMPILER_RT_ENABLE_TVOS=Off -DCOMPILER_RT_ENABLE_WATCHOS=Off -DCOMPILER_RT_ENABLE_IOS=Off -DCOMPILER_RT_INCLUDE_TESTS=Off -DPYTHON_EXECUTABLE=/usr/bin/python3 -DLLVM_ENABLE_BINDINGS=Off -G Ninja  ../llvm-project/llvm/

on Ubuntu 20.10, clang-11 from the LLVM dpkg 
tests run:
ninja check-clang

**Comment by bcardosolopes** [comment]
Thanks for reporting this @steve-downey, those are known issues to-be-implemented - we haven't focused yet on getting the  matchers right, will take the opportunity and silence these for now.

**Comment by dansarginson** [comment]
@bcardosolopes as Steve says there are also some failing tests in other files that I can't account for. Quite a few are in OpenMP code. All of the test failures are [assertion failures](https://github.com/bcardosolopes/llvm-project/blob/llvmorg-master-pattern-matching/clang/lib/Parse/ParseExprCXX.cpp#L3935) when we find ourselves parsing an inspect expression without an inspect keyword. This is somewhat surprising to me as I can only find a [single call to ParseInspectExpr](https://github.com/bcardosolopes/llvm-project/blob/llvmorg-master-pattern-matching/clang/lib/Parse/ParseExpr.cpp#L1692), immediately after detecting an inspect keyword.

I'm doing some work bisecting the test files themselves to understand which tests are triggering the assertion. Will report back.

**Comment by dansarginson** [comment]
Aha, got it. [This fallthrough](https://github.com/bcardosolopes/llvm-project/blob/llvmorg-master-pattern-matching/clang/lib/Parse/ParseExpr.cpp#L1690) from parsing l_square is the culprit. I'll prepare a PR.
